version: "3.9"
name: wireguard
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="Europe/Madrid"
#      - SERVERURL=wireguard.domain.com #optional
      - SERVERPORT=49300 #optional
      - PEERS=${VPN_PEERS}
      - PEERDNS=192.168.1.70 #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0, 192.168.1.0/24 #optional
      - PERSISTENTKEEPALIVE_PEERS=all #optional
      - LOG_CONFS=true #optional
    volumes:
      - ${CONFIG_PATH}:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 49300:51820/udp
    restart: unless-stopped