version: "3.9"
name: prowlarr_stack
services:
   radarr:
    container_name: Prowlarr
    image: linuxserver/prowlarr:latest
    networks:
      - default
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
    ports:
      - 9696:9696
    volumes:
      - ${CONFIG_PATH}:/config
    restart: "no"
      
networks:
  default:
    external: true
    name: ${NETWORK}
