version: "3.9"
name: jellyfin_stack
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    networks:
      - default
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
    supplementalGroups:
      - "105"
    volumes:
      - ${CONFIG_PATH}:/config
      - ${CACHE_PATH}:/cache
      - ${MEDIA_PATH}:/media
    ports:
      - "8096:8096"
    restart: "no"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128

networks:
  default:
    external: true
    name: ${NETWORK}
