- name: check if swap file exists
  stat:
    path: "{{ item.path }}"
  register: swap_file_check

- name: create swap file
  command: fallocate -l {{ item.size }} {{ item.path }}
  when: not swap_file_check.stat.exists

- name: Create swap space
  command: dd if=/dev/zero of=/extraswap bs=1M count=512
  when: not swap_file_check.stat.exists

- name: set permissions on swap file
  file:
    path: "{{ item.path }}"
    mode: 0600

- name: format swap file
  command: mkswap {{ item.path }}
  when: not swap_file_check.stat.exists

- name: add to fstab
  lineinfile:
    dest: /etc/fstab
    regexp: "{{ item.path }}"
    line: "{{ item.path }} none swap sw 0 0"

- name: turn on swap
  command: swapon -a

- name: set swapiness
  sysctl:
    name: vm.swappiness
    value: "1"
