services:
  hosts:
    zeus: 
      ansible_host: 10.10.5.50
      ansible_user: admin_user

NAS:
  hosts:
    zeus:
      server01:
        ansible_host: 10.10.5.50
        ansible_user: admin_user
  vars:
    nfs_exports: [ "/mnt/Merged_all/NAS *(rw,async,no_root_squash)" ]
