---
- hosts: server01
  become: yes
  tasks:
    - name: Install samba
      apt:
        name:
          - samba
        state: present
        update_cache: yes


    - name: samba_users | creating samba user passwords # noqa 301 306
      shell: "(echo {{ item['smbpasswd'] }}; echo {{ item['smbpasswd'] }}) | smbpasswd -s -a {{ item['name'] }}"
      become: true
      with_items: "{{ samba_users }}"
