version: "3.9"
name: "lldap"
services:
  lldap:
    image: lldap/lldap:latest
    ports:
      # For LDAP, not recommended to expose, see Usage section.
      #- "3890:3890"
      # For LDAPS (LDAP Over SSL), enable port if LLDAP_LDAPS_OPTIONS__ENABLED set true, look env below
      #- "6360:6360"
      # For the web front-end
      - "17170:17170"
    networks:
      - default
      - ldap_network
    volumes:
      - "${CONFIG_PATH}:/data"
      # Alternatively, you can mount a local folder
      # - "./lldap_data:/data"
    environment:
      - UID1000
      - GID1000
      - TZ=CET
      - LLDAP_JWT_SECRET=${JWT_SECRET}
      - LLDAP_KEY_SEED=${SEED}
      - LLDAP_LDAP_BASE_DN=dc=almr,dc=com
      - LLDAP_LDAP_USER_DN=admin
      - LLDAP_LDAP_USER_PASS=${ADMIN_PASSWORD}
      # If using LDAPS, set enabled true and configure cert and key path
      # - LLDAP_LDAPS_OPTIONS__ENABLED=true
      # - LLDAP_LDAPS_OPTIONS__CERT_FILE=/path/to/certfile.crt
      # - LLDAP_LDAPS_OPTIONS__KEY_FILE=/path/to/keyfile.key
      # You can also set a different database:
      - LLDAP_DATABASE_URL=mysql://${MDB_user}:${MDB_pswd}@{MARIADB_IP}/ldap
      #- LLDAP_DATABASE_URL=postgres://postgres-user:password@postgres-server/my-database

networks:
  default:
    external: true
    name: ${NETWORK}
  ldap_network:
    name: ldap_network # This line is not allowed to be changed as otherwise the created network will not be used by the other containers of AIO
    driver: bridge