version: "3.9"
name: radarr_stack
services:
   radarr:
    container_name: Radarr
    image: lscr.io/linuxserver/radarr:latest
    networks:
      - ${NETWORK}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
    ports:
      - 7878:7878
    volumes:
      - ${CONFIG_PATH}:/config
      - ${MEDIA_PATH}:/Media
    restart: "unless-stopped"
      
networks:
  ${NETWORK}:
