version: "3.9"
name: sonarr_stack
services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - default
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
    volumes:
      - ${CONFIG_PATH}:/config
      - ${MEDIA_PATH}:/Media
    ports:
      - 8989:8989
    restart: "no"

networks:
  default:
    external: true
    name: ${NETWORK}
