version: "3.9"
name: mariadb
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MDB_root_pswd}
      MYSQL_DATABASE: ${MDB_DB}
      MYSQL_USER: ${MDB_user}
      MYSQL_PASSWORD: ${MDB_pswd}
    volumes:
      - ${APP_DATA}:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: "always"
