version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    networks:
      - default
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
    volumes:
      - ${CONFIG_PATH}:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: "unless-stopped"
      #privileged: true
  
networks:
  default:
    external: true
    name: ${NETWORK}
