version: '3.9'
name: home_assistant
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    network_mode: "host"        
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
    volumes:
      - ${CONFIG_PATH}:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    ports:
      - 8123:8123
      - 5683:5683/udp
    restart: "unless-stopped"
      #privileged: true
