version: '3.9'
name: "nginx-proxy-manager"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${CONFIG_PATH}:/data
      - ${APP_DATA}:/etc/letsencrypt